# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'MediaPipeTasksCommon', '~> 0.10.14'
  pod 'MediaPipeTasksVision', '0.10.14'
  pod 'onnxruntime-objc', '1.14.0'
end
